import Providers from '@/components/Providers'
import Navbar from '@/components/ui/Navbar'
import { Toaster } from '@/components/ui/Toaster'
import { cn } from '@/lib/utils'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google' // Wix_Madefor_Text  |  Geologica

const font = Inter({
  subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
  title: 'Веб-форум ЄУ',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  authModal,
}: Readonly<{
  children: React.ReactNode
  authModal: React.ReactNode
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="uk"
      className={cn('antialiased', font.className)}
    >
      <body className="min-h-screen">
        <Providers>
          <Navbar />

          {authModal}

          <div className="container mx-auto h-full max-w-7xl pt-24">
            {children}
          </div>

          <Toaster />
        </Providers>
      </body>
    </html>
  )
}
